### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by MACCK-CT** [pdeitel/PythonFundamentalsLiveLessons#1]
Hi,

I'm new to python and trying to execute the code in chapter 2 but I am receiving the following errors:

In [3]: ipython fig02_01.py
  File "<ipython-input-3-c987980fc388>", line 1
    ipython fig02_01.py
                   ^
SyntaxError: invalid syntax

In [4]: ipython fig02_02.py
  File "<ipython-input-4-de90a1fff3d7>", line 1
    ipython fig02_02.py
                   ^
SyntaxError: invalid syntax

I did not modify the code, just trying to call it.  Not sure what I am doing wrong.

Thanks

**Comment by IB72** [comment]
It would appear that you are trying to run the program from the IPython interactive mode.
Exit the interactive mode by pressing "Ctrl + D" if running the Anaconda prompt on Windows and run the program again from there just as you called the code above.

Disclaimer: I am not acting on behalf of Mr. and Mr. Deitel - I am also following along with this great resource.

Attemptying to call the program from IPython interactive mode:
![Capture](https://user-images.githubusercontent.com/32449797/80299758-e1b40a80-878e-11ea-91c6-beb02b1970c5.PNG)

Calling the code with the IPython command outside of interactive mode:
![Capture2](https://user-images.githubusercontent.com/32449797/80299811-3ce5fd00-878f-11ea-8f51-2a735f50bfb4.PNG)

**Comment by MACCK-CT** [comment]
Hi, 
You are correct, I was still in ipython interactive mode from the previous lab.  After I exited I was able to run the program.

Thanks
